### ISSUE TITLE
Change the SOAP11 API to be consistent with SOAP12

### ISSUE THREAD

**Issue by Bhashinee** [wso2-ballerina/module-soap#65]
**Description:**
Current implementation is as follows,

SOAP 11 endpoint
`public remote function sendReceive(string soapAction, xml | mime:Entity[] body, Options? options = ())`

SOAP 12 endpoint
`public remote function sendReceive(xml | mime:Entity[] body, string? soapAction = (), Options? options = ())`

It was suggested to swap the `body` and `soapAction` in SOAP11 endpoint to be consistent with the SOAP 12 endpoint.

**Comment by Maninda** [comment]
New changes are available from version 0.4.2.
